# Generated by Django 3.2.9 on 2021-11-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varta', '0003_auto_20211128_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
